#ifndef RESTAURANT_FINDERLIB_GLOBAL_H
#define RESTAURANT_FINDERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RESTAURANT_FINDERLIB_LIBRARY)
#  define RESTAURANT_FINDERLIB_EXPORT Q_DECL_EXPORT
#else
#  define RESTAURANT_FINDERLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // RESTAURANT_FINDERLIB_GLOBAL_H
